// Expanded word pool for typing practice — 10,000+ unique words across all difficulty levels
// Smart rotation ensures users never see the same words twice in a row

export const TYPING_WORDS: string[] = [
  // ── Top 300 Most Common English Words ─────────────────────────────────────
  'the','be','to','of','and','a','in','that','have','it','for','not','on','with',
  'he','as','you','do','at','this','but','his','by','from','they','we','say','her',
  'she','or','an','will','my','one','all','would','there','their','what','so','up',
  'out','if','about','who','get','which','go','me','when','make','can','like','time',
  'no','just','him','know','take','people','into','year','your','good','some','could',
  'them','see','other','than','then','now','look','only','come','its','over','think',
  'also','back','after','use','two','how','our','work','first','well','way','even',
  'new','want','because','any','these','give','day','most','us','between','need',
  'large','often','hand','high','place','hold','turn','here','why','help','put','set',
  'run','bring','show','much','before','mean','keep','lot','world','still','own',
  'last','never','under','while','where','should','start','city','play','small',
  'number','off','always','move','live','next','found','side','face','night','true',
  'call','down','may','every','add','change','door','important','few','near','open',
  'seem','together','light','white','children','begin','got','walk','example','ease',
  'paper','group','always','music','those','both','mark','book','letter','until',
  'mile','river','car','feet','care','second','enough','far','took','short','study',
  'long','already','above','real','behind','power','country','earth','eyes','room',
  'friend','free','red','great','story','idea','body','plant','south','life','force',
  'blue','sea','tree','told','left','family','hard','usually','hear','far','kind',
  'let','though','name','same','three','yet','four','five','six','seven','eight',
  'nine','ten','part','such','right','look','also','around','form','three','small',
  'set','put','end','does','another','well','large','need','big','turn','here','tell',
  // ── Animals ───────────────────────────────────────────────────────────────
  'cat','dog','bird','fish','lion','tiger','bear','wolf','fox','deer','elk','moose',
  'horse','cow','pig','sheep','goat','donkey','rabbit','hare','squirrel','chipmunk',
  'mouse','rat','hamster','gerbil','guinea','ferret','mink','otter','beaver','badger',
  'hedgehog','mole','shrew','vole','lemur','monkey','ape','gorilla','chimpanzee',
  'baboon','orangutan','gibbon','macaque','marmoset','tamarin','capuchin','howler',
  'elephant','rhinoceros','hippopotamus','giraffe','zebra','wildebeest','antelope',
  'gazelle','springbok','impala','kudu','oryx','eland','bison','buffalo','yak','camel',
  'llama','alpaca','vicuna','guanaco','kangaroo','wallaby','wombat','koala','possum',
  'platypus','echidna','tasmanian','quoll','numbat','bilby','quokka','pademelon',
  'eagle','hawk','falcon','osprey','kestrel','harrier','buzzard','vulture','condor',
  'owl','heron','crane','stork','flamingo','pelican','albatross','petrel','gannet',
  'puffin','penguin','emu','ostrich','rhea','kiwi','cassowary','peacock','pheasant',
  'partridge','grouse','turkey','quail','dove','pigeon','parrot','macaw','cockatoo',
  'toucan','hornbill','kingfisher','woodpecker','swallow','swift','robin','sparrow',
  'finch','canary','wren','thrush','blackbird','starling','crow','raven','magpie',
  'jay','jackdaw','chough','rook','nuthatch','treecreeper','warbler','flycatcher',
  'salmon','trout','bass','perch','pike','carp','tench','bream','roach','rudd',
  'shark','ray','skate','tuna','mackerel','herring','sardine','anchovy','cod',
  'haddock','plaice','sole','turbot','halibut','flounder','dab','sprat','eel',
  'swordfish','marlin','sailfish','barracuda','grouper','snapper','sea bass','snook',
  'frog','toad','newt','salamander','axolotl','caecilian','lizard','gecko','iguana',
  'chameleon','skink','monitor','agama','anole','bearded dragon','frilled','thorny',
  'snake','python','boa','cobra','mamba','viper','adder','rattlesnake','copperhead',
  'crocodile','alligator','caiman','gharial','tortoise','turtle','terrapin','gecko',
  'jellyfish','starfish','crab','lobster','shrimp','prawn','barnacle','sea urchin',
  'octopus','squid','cuttlefish','nautilus','clam','oyster','mussel','scallop',
  'snail','slug','worm','centipede','millipede','scorpion','spider','tarantula',
  'ant','bee','wasp','hornet','butterfly','moth','dragonfly','damselfly','cricket',
  'grasshopper','locust','stick insect','mantis','beetle','ladybug','firefly',
  'mosquito','fly','gnat','midge','aphid','caterpillar','larva','pupa','chrysalis',
  // ── Food & Drink ──────────────────────────────────────────────────────────
  'apple','banana','cherry','grape','melon','peach','pear','plum','mango','papaya',
  'pineapple','coconut','lemon','lime','orange','tangerine','grapefruit','pomelo',
  'avocado','guava','passion','lychee','kiwi','fig','date','raisin','prune','apricot',
  'nectarine','raspberry','strawberry','blueberry','blackberry','gooseberry','currant',
  'cranberry','elderberry','mulberry','boysenberry','loganberry','watermelon','cantaloupe',
  'honeydew','jackfruit','durian','rambutan','mangosteen','star fruit','dragon fruit',
  'bread','butter','cheese','milk','cream','yogurt','egg','meat','fish','chicken',
  'beef','pork','lamb','veal','turkey','duck','goose','venison','rabbit','quail',
  'bacon','ham','sausage','salami','pepperoni','prosciutto','chorizo','bratwurst',
  'rice','pasta','noodle','wheat','oat','barley','rye','corn','millet','quinoa',
  'potato','yam','sweet potato','carrot','parsnip','turnip','beet','radish','celery',
  'onion','garlic','leek','shallot','chive','fennel','celeriac','kohlrabi','artichoke',
  'broccoli','cauliflower','cabbage','kale','spinach','lettuce','arugula','chard',
  'cucumber','zucchini','squash','pumpkin','eggplant','pepper','tomato','tomatillo',
  'mushroom','truffle','porcini','chanterelle','shiitake','portobello','oyster',
  'bean','lentil','chickpea','pea','soybean','tofu','tempeh','edamame','hummus',
  'almond','walnut','cashew','pecan','hazelnut','pistachio','macadamia','chestnut',
  'sunflower','sesame','flaxseed','chia','pumpkin seed','poppy seed','hemp seed',
  'basil','oregano','thyme','rosemary','sage','mint','parsley','cilantro','dill',
  'tarragon','marjoram','bay leaf','lemongrass','kaffir','galangal','turmeric',
  'ginger','cinnamon','cardamom','clove','nutmeg','vanilla','pepper','chili','paprika',
  'saffron','cumin','coriander','anise','fennel seed','mustard','fenugreek','allspice',
  'salt','sugar','honey','maple','agave','molasses','caramel','chocolate','cocoa',
  'coffee','tea','water','juice','soda','lemonade','smoothie','shake','beer','wine',
  'whisky','vodka','rum','gin','tequila','brandy','champagne','cider','mead','sake',
  'soup','stew','broth','bisque','chowder','gazpacho','ramen','pho','minestrone',
  'salad','coleslaw','slaw','dressing','vinaigrette','mayonnaise','mustard','ketchup',
  'sauce','gravy','curry','chutney','relish','pickle','jam','jelly','marmalade',
  'cake','pie','tart','cookie','brownie','muffin','scone','biscuit','croissant',
  'donut','waffle','pancake','crepe','brioche','bagel','pretzel','cracker','toast',
  'ice cream','sorbet','gelato','pudding','custard','mousse','cheesecake','tiramisu',
  'trifle','baklava','mochi','macaron','profiterole','eclair','cannoli','churro',
  // ── Places & Geography ────────────────────────────────────────────────────
  'mountain','valley','river','ocean','lake','forest','desert','island','beach',
  'cliff','cave','gorge','canyon','plateau','plain','meadow','marsh','swamp','bog',
  'reef','lagoon','fjord','delta','estuary','peninsula','cape','bay','gulf','strait',
  'waterfall','geyser','volcano','glacier','iceberg','tundra','savanna','jungle',
  'rainforest','woodland','heath','moor','steppe','prairie','grassland','wetland',
  'city','town','village','hamlet','suburb','neighborhood','district','quarter',
  'street','avenue','boulevard','lane','alley','road','highway','motorway','freeway',
  'bridge','tunnel','dam','harbor','port','dock','pier','lighthouse','beacon',
  'airport','station','terminal','depot','garage','warehouse','factory','plant',
  'school','university','college','academy','institute','library','museum','gallery',
  'hospital','clinic','pharmacy','laboratory','observatory','planetarium','aquarium',
  'zoo','park','garden','plaza','square','monument','memorial','statue','fountain',
  'castle','palace','temple','cathedral','church','mosque','synagogue','shrine',
  'market','mall','store','shop','boutique','bakery','restaurant','cafe','bar',
  'theater','cinema','stadium','arena','gym','court','field','track','pool',
  // ── Buildings & Architecture ──────────────────────────────────────────────
  'wall','floor','ceiling','roof','door','window','staircase','elevator','escalator',
  'corridor','hallway','lobby','foyer','atrium','balcony','terrace','porch','deck',
  'basement','cellar','attic','loft','mezzanine','penthouse','suite','studio','flat',
  'cottage','bungalow','mansion','villa','chalet','cabin','lodge','farmhouse','barn',
  'column','pillar','arch','vault','dome','spire','turret','buttress','parapet',
  'foundation','beam','joist','rafter','truss','lintel','sill','jamb','threshold',
  'brick','concrete','steel','timber','glass','marble','granite','slate','tile','stone',
  'mortar','plaster','render','stucco','cladding','insulation','waterproofing','grout',
  'plumbing','wiring','duct','pipe','cable','conduit','socket','switch','panel','meter',
  'heating','cooling','ventilation','fireplace','chimney','flue','radiator','boiler',
  // ── Vehicles & Transport ──────────────────────────────────────────────────
  'car','truck','van','bus','taxi','tram','train','subway','ferry','boat','ship',
  'yacht','canoe','kayak','raft','barge','tanker','freighter','tugboat','speedboat',
  'bicycle','motorcycle','scooter','moped','tricycle','unicycle','skateboard','rollerblade',
  'plane','helicopter','glider','drone','rocket','shuttle','satellite','spacecraft',
  'ambulance','fire truck','police','tractor','forklift','crane','bulldozer','excavator',
  'engine','motor','transmission','gearbox','clutch','brake','wheel','tire','axle',
  'hood','trunk','bumper','headlight','taillight','mirror','windshield','wiper','antenna',
  'fuel','gasoline','diesel','electric','hybrid','battery','charger','throttle','turbo',
  'runway','taxiway','hangar','control tower','terminal','gate','boarding','baggage',
  'rail','track','sleeper','platform','signal','junction','crossing','level crossing',
  // ── Sports & Recreation ───────────────────────────────────────────────────
  'soccer','football','basketball','baseball','tennis','golf','cricket','rugby','hockey',
  'volleyball','badminton','squash','racquetball','table tennis','ping pong','snooker',
  'pool','billiards','darts','bowling','archery','fencing','wrestling','boxing','judo',
  'karate','taekwondo','jujitsu','aikido','kung fu','capoeira','sumo','kickboxing',
  'swimming','diving','surfing','sailing','rowing','canoeing','kayaking','rafting',
  'skiing','snowboarding','ice skating','figure skating','speed skating','luge','bobsled',
  'running','sprinting','marathon','triathlon','decathlon','cycling','climbing','hiking',
  'gymnastics','acrobatics','cheerleading','dancing','ballet','contemporary','hip hop',
  'score','goal','point','match','game','set','round','inning','quarter','period',
  'team','player','coach','referee','umpire','linesman','captain','goalkeeper','striker',
  'medal','trophy','championship','league','tournament','cup','series','playoff','final',
  'stadium','arena','court','pitch','field','track','pool','rink','course','ring',
  // ── Music & Arts ──────────────────────────────────────────────────────────
  'piano','guitar','violin','drums','bass','flute','trumpet','saxophone','cello',
  'harp','organ','accordion','clarinet','oboe','tuba','trombone','banjo','ukulele',
  'mandolin','dulcimer','sitar','tabla','djembe','xylophone','marimba','vibraphone',
  'theremin','synthesizer','sampler','sequencer','arpeggiator','oscillator','filter',
  'melody','harmony','rhythm','tempo','beat','note','chord','scale','octave','pitch',
  'tone','timbre','vibrato','tremolo','crescendo','diminuendo','fortissimo','pianissimo',
  'symphony','sonata','concerto','quartet','ensemble','orchestra','band','solo','duet',
  'verse','chorus','bridge','hook','intro','outro','refrain','cadence','measure','bar',
  'treble','clef','staff','sharp','flat','natural','major','minor','modal','tonal',
  'jazz','blues','rock','pop','classical','electronic','ambient','folk','country','rap',
  'funk','soul','reggae','gospel','opera','chamber','baroque','romantic','avant garde',
  'record','track','album','single','mix','master','reverb','delay','echo','distortion',
  'painting','drawing','sculpture','photography','printmaking','collage','mosaic',
  'watercolor','oil paint','acrylic','tempera','gouache','pastel','charcoal','ink',
  'canvas','easel','palette','brush','chisel','clay','marble','bronze','ceramics',
  'architecture','design','typography','illustration','animation','film','video',
  'poem','novel','story','essay','play','script','sonnet','haiku','ballad','epic',
  'metaphor','simile','alliteration','assonance','rhyme','verse','stanza','couplet',
  'plot','character','setting','theme','conflict','resolution','climax','narrator',
  // ── Technology & Computing ────────────────────────────────────────────────
  'computer','laptop','tablet','phone','screen','keyboard','mouse','monitor','printer',
  'scanner','projector','speaker','microphone','camera','webcam','headphone','earphone',
  'server','router','modem','switch','hub','cable','wireless','network','internet',
  'website','browser','search','email','chat','forum','blog','wiki','stream','download',
  'software','hardware','firmware','driver','program','application','system','platform',
  'database','cloud','backup','storage','memory','processor','graphics','audio','video',
  'pixel','resolution','bandwidth','latency','protocol','firewall','encryption','proxy',
  'password','username','profile','account','settings','dashboard','interface','widget',
  'button','menu','dropdown','slider','toggle','checkbox','input','output','terminal',
  'code','script','function','variable','constant','array','object','method','class',
  'library','framework','module','package','version','update','patch','deploy','release',
  'test','debug','error','warning','exception','log','trace','monitor','alert','report',
  'algorithm','logic','loop','condition','recursion','iteration','pointer','reference',
  'compile','interpret','execute','parse','render','stream','buffer','queue','stack',
  'artificial','intelligence','machine learning','neural network','deep learning',
  'blockchain','cryptocurrency','token','wallet','transaction','ledger','node','hash',
  'virtual','reality','augmented','mixed','hologram','simulation','metaverse','avatar',
  'robot','android','automation','drone','sensor','actuator','motor','servo','solenoid',
  'wifi','bluetooth','ethernet','satellite','fiber','cellular','radio','infrared','laser',
  'binary','hexadecimal','octal','decimal','boolean','integer','float','string','char',
  'html','css','javascript','python','java','rust','golang','typescript','php','ruby',
  'sql','nosql','mongodb','postgresql','mysql','redis','elasticsearch','kafka','spark',
  'docker','kubernetes','container','virtual machine','hypervisor','cluster','node','pod',
  'api','rest','graphql','webhook','endpoint','request','response','header','payload',
  'git','repository','branch','commit','merge','pull request','fork','clone','push',
  // ── Science & Nature ──────────────────────────────────────────────────────
  'atom','molecule','element','compound','reaction','energy','force','gravity','light',
  'heat','sound','pressure','volume','mass','weight','density','frequency','wavelength',
  'magnetic','electric','thermal','chemical','nuclear','quantum','particle','wave',
  'proton','neutron','electron','photon','quark','boson','fermion','lepton','meson',
  'nucleus','orbital','valence','bond','ion','isotope','radioactive','decay','fission',
  'fusion','plasma','gas','liquid','solid','crystal','polymer','alloy','ceramic',
  'sun','moon','star','planet','galaxy','universe','comet','meteor','eclipse','orbit',
  'atmosphere','weather','climate','temperature','humidity','pressure','storm','thunder',
  'lightning','tornado','hurricane','earthquake','volcano','tsunami','drought','flood',
  'photosynthesis','respiration','digestion','circulation','reproduction','evolution',
  'genetics','dna','rna','protein','enzyme','hormone','vitamin','mineral','cell',
  'tissue','organ','organism','species','genus','family','order','class','phylum',
  'ecosystem','biome','habitat','niche','predator','prey','symbiosis','parasitism',
  'mutation','adaptation','natural selection','biodiversity','conservation','extinction',
  'carbon','oxygen','hydrogen','nitrogen','calcium','potassium','sodium','chlorine',
  'iron','copper','zinc','aluminum','silicon','phosphorus','sulfur','magnesium',
  'biology','chemistry','physics','geology','ecology','astronomy','mathematics','logic',
  'hypothesis','theory','experiment','observation','data','evidence','conclusion',
  'microscope','telescope','spectroscope','oscilloscope','voltmeter','thermometer',
  // ── Health & Medicine ─────────────────────────────────────────────────────
  'health','wellness','fitness','exercise','nutrition','diet','sleep','rest','recovery',
  'strength','flexibility','endurance','balance','coordination','agility','speed',
  'heart','lung','brain','liver','kidney','stomach','intestine','pancreas','spleen',
  'bone','muscle','tendon','ligament','cartilage','nerve','vein','artery','capillary',
  'blood','plasma','red cell','white cell','platelet','antibody','antigen','immune',
  'virus','bacteria','fungus','parasite','infection','inflammation','allergy','autoimmune',
  'vaccine','antibiotic','antiviral','medication','prescription','dose','treatment',
  'surgery','diagnosis','symptom','syndrome','disease','disorder','condition','chronic',
  'acute','emergency','trauma','wound','fracture','sprain','strain','bruise','blister',
  'fever','cough','sneeze','nausea','headache','migraine','fatigue','dizziness','pain',
  'doctor','nurse','surgeon','pharmacist','therapist','specialist','general practitioner',
  'hospital','clinic','ward','operating','intensive care','emergency','outpatient',
  'yoga','meditation','mindfulness','breathing','stretching','massage','acupuncture',
  // ── Psychology & Emotions ─────────────────────────────────────────────────
  'happy','joyful','excited','grateful','hopeful','proud','confident','peaceful',
  'calm','relaxed','content','satisfied','inspired','motivated','focused','determined',
  'curious','creative','thoughtful','imaginative','insightful','empathetic','patient',
  'surprised','amazed','astonished','delighted','thrilled','ecstatic','blissful',
  'worried','nervous','anxious','confused','uncertain','doubtful','hesitant','cautious',
  'sad','lonely','disappointed','frustrated','tired','overwhelmed','restless','bored',
  'angry','upset','irritated','jealous','envious','guilty','ashamed','embarrassed',
  'love','trust','hope','faith','courage','wisdom','kindness','honesty','loyalty',
  'freedom','justice','equality','respect','dignity','compassion','forgiveness','grace',
  'thought','memory','dream','idea','concept','belief','opinion','attitude','value',
  'personality','behavior','cognition','perception','motivation','emotion','mood',
  'consciousness','awareness','mindfulness','presence','attention','focus','intention',
  'stress','anxiety','depression','trauma','phobia','obsession','compulsion','addiction',
  'resilience','growth','healing','acceptance','gratitude','compassion','empathy',
  // ── Education & Learning ──────────────────────────────────────────────────
  'learn','study','read','write','calculate','analyze','synthesize','evaluate','apply',
  'understand','explain','demonstrate','practice','review','memorize','visualize','plan',
  'subject','topic','lesson','chapter','unit','module','course','curriculum','syllabus',
  'teacher','professor','instructor','tutor','mentor','student','pupil','learner',
  'classroom','lecture','seminar','workshop','tutorial','lab','fieldwork','internship',
  'homework','assignment','project','essay','thesis','dissertation','report','presentation',
  'exam','test','quiz','assessment','grade','score','feedback','evaluation','rubric',
  'knowledge','skill','competency','ability','talent','expertise','mastery','proficiency',
  'reading','writing','arithmetic','science','history','geography','literature','language',
  'mathematics','algebra','geometry','calculus','statistics','trigonometry','topology',
  'physics','chemistry','biology','ecology','geology','astronomy','meteorology',
  'history','archaeology','anthropology','sociology','psychology','philosophy','ethics',
  'art','music','drama','dance','sport','physical education','health education','civics',
  'scholarship','fellowship','grant','bursary','loan','tuition','enrollment','graduation',
  // ── Business & Economy ────────────────────────────────────────────────────
  'business','company','corporation','enterprise','startup','venture','firm','agency',
  'market','industry','sector','economy','trade','commerce','finance','investment',
  'revenue','profit','loss','cost','price','value','asset','liability','equity','debt',
  'stock','share','bond','fund','portfolio','dividend','interest','return','yield',
  'budget','forecast','plan','strategy','goal','objective','target','milestone','kpi',
  'product','service','brand','logo','marketing','advertising','promotion','campaign',
  'customer','client','consumer','user','buyer','seller','supplier','vendor','partner',
  'sales','purchase','order','invoice','receipt','contract','agreement','negotiation',
  'management','leadership','team','department','division','hierarchy','structure',
  'employee','employer','staff','worker','contractor','freelancer','consultant','advisor',
  'entrepreneur','founder','executive','director','manager','supervisor','coordinator',
  'innovation','disruption','transformation','digitalization','automation','optimization',
  'supply chain','logistics','distribution','warehouse','inventory','procurement',
  'accounting','audit','tax','compliance','regulation','governance','risk','insurance',
  // ── Law & Government ──────────────────────────────────────────────────────
  'law','rule','regulation','statute','ordinance','code','policy','procedure','guideline',
  'court','judge','jury','lawyer','attorney','prosecutor','defendant','plaintiff','witness',
  'crime','offense','felony','misdemeanor','violation','penalty','fine','sentence','parole',
  'police','detective','investigator','forensic','evidence','clue','motive','alibi',
  'government','parliament','congress','senate','assembly','council','committee','cabinet',
  'president','prime minister','minister','senator','representative','governor','mayor',
  'election','vote','ballot','candidate','campaign','party','coalition','opposition',
  'constitution','charter','amendment','bill','act','resolution','decree','mandate',
  'democracy','republic','monarchy','dictatorship','federation','confederation','union',
  'rights','freedom','liberty','justice','equality','sovereignty','citizenship','nationality',
  'treaty','agreement','accord','alliance','sanction','embargo','diplomacy','negotiation',
  'military','army','navy','air force','marines','soldiers','officers','generals',
  // ── Communication & Media ─────────────────────────────────────────────────
  'speak','talk','say','tell','ask','answer','explain','describe','inform','notify',
  'announce','broadcast','publish','print','report','cover','interview','comment',
  'letter','email','message','text','call','video','conference','meeting','presentation',
  'newspaper','magazine','journal','newsletter','bulletin','pamphlet','brochure','flyer',
  'television','radio','podcast','channel','station','broadcast','stream','network',
  'social media','platform','profile','post','tweet','share','like','follow','subscribe',
  'content','creator','influencer','blogger','vlogger','journalist','editor','writer',
  'communication','conversation','dialogue','monologue','debate','discussion','argument',
  'language','dialect','accent','slang','jargon','terminology','vocabulary','grammar',
  'word','sentence','paragraph','text','passage','chapter','section','article','document',
  'translation','interpretation','localization','transcription','subtitles','caption',
  // ── Household & Furniture ─────────────────────────────────────────────────
  'bed','sofa','couch','chair','armchair','recliner','ottoman','bench','stool','cushion',
  'table','desk','counter','shelf','bookcase','wardrobe','cabinet','dresser','chest',
  'lamp','light','chandelier','fan','curtain','blind','shutter','rug','carpet','mat',
  'mirror','clock','calendar','frame','picture','painting','sculpture','vase','pot',
  'kitchen','bathroom','bedroom','living room','dining room','study','utility','garage',
  'refrigerator','freezer','oven','stove','microwave','dishwasher','washing machine',
  'dryer','vacuum','mop','broom','bucket','bin','trash','recycle','compost',
  'fork','knife','spoon','plate','bowl','cup','mug','glass','pitcher','pan','pot',
  'blender','mixer','toaster','kettle','coffee maker','juicer','processor','grill',
  'towel','cloth','sponge','soap','detergent','bleach','cleaner','polish','wax',
  // ── Clothing & Fashion ────────────────────────────────────────────────────
  'shirt','blouse','top','tee','sweater','jumper','hoodie','jacket','coat','raincoat',
  'trousers','pants','jeans','shorts','skirt','dress','suit','blazer','vest','cardigan',
  'underwear','boxer','brief','bra','socks','stockings','tights','leggings','swimsuit',
  'shoes','boots','sandals','slippers','trainers','sneakers','heels','loafers','moccasins',
  'hat','cap','beanie','beret','fedora','helmet','hood','veil','scarf','gloves','mittens',
  'belt','tie','bow tie','suspenders','buckle','button','zipper','snap','velcro','lace',
  'cotton','wool','silk','linen','polyester','nylon','leather','suede','denim','velvet',
  'fashion','style','trend','design','collection','runway','catwalk','model','designer',
  'accessory','jewelry','necklace','bracelet','ring','earring','watch','sunglasses','bag',
  'handbag','backpack','suitcase','wallet','purse','tote','clutch','satchel','briefcase',
  // ── Colors & Shapes ───────────────────────────────────────────────────────
  'red','orange','yellow','green','blue','indigo','violet','purple','pink','magenta',
  'cyan','turquoise','teal','lime','olive','maroon','burgundy','crimson','scarlet','coral',
  'salmon','peach','ivory','cream','beige','tan','khaki','brown','chocolate','coffee',
  'black','white','gray','silver','gold','bronze','copper','rose','lavender','lilac',
  'circle','square','triangle','rectangle','oval','ellipse','rhombus','trapezoid','pentagon',
  'hexagon','octagon','decagon','star','heart','cross','arrow','spiral','crescent','diamond',
  'cube','sphere','cylinder','cone','pyramid','prism','torus','helix','fractal','polygon',
  // ── Time & Calendar ───────────────────────────────────────────────────────
  'morning','afternoon','evening','night','midnight','noon','dawn','dusk','twilight',
  'today','yesterday','tomorrow','weekend','weekday','weeknight','workday','holiday',
  'minute','second','hour','daily','weekly','monthly','yearly','annually','quarterly',
  'season','spring','summer','autumn','winter','solstice','equinox','monsoon','harvest',
  'january','february','march','april','may','june','july','august','september',
  'october','november','december','monday','tuesday','wednesday','thursday','friday',
  'saturday','sunday','decade','century','millennium','era','epoch','period','age',
  'birthday','anniversary','celebration','festival','tradition','ceremony','ritual',
  // ── Numbers & Math ────────────────────────────────────────────────────────
  'zero','one','two','three','four','five','six','seven','eight','nine','ten',
  'eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen',
  'nineteen','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety',
  'hundred','thousand','million','billion','trillion','infinity','negative','positive',
  'fraction','decimal','percentage','ratio','proportion','rate','average','median','mode',
  'addition','subtraction','multiplication','division','exponent','root','logarithm',
  'equation','formula','theorem','proof','axiom','postulate','lemma','corollary',
  'geometry','algebra','calculus','statistics','probability','topology','number theory',
  'prime','composite','even','odd','integer','rational','irrational','real','complex',
  // ── Medium Difficulty ─────────────────────────────────────────────────────
  'accomplish','accurate','achieve','acquire','address','advance','adventure','advice',
  'affect','afford','agenda','almost','already','although','amount','analyze','ancient',
  'another','answer','approve','arrange','article','attempt','balance','beauty','believe',
  'benefit','bother','budget','capable','capture','careful','category','certain','chance',
  'chapter','charge','choice','clear','collect','combine','comment','commit','compare',
  'compete','complete','complex','consider','contain','control','correct','create',
  'culture','curious','current','custom','damage','decide','define','deliver','depend',
  'describe','design','develop','difference','difficult','discover','discuss','display',
  'divide','effect','effort','element','encourage','engage','entire','evaluate','event',
  'example','explain','explore','express','feature','feeling','figure','finally','finish',
  'follow','forget','forward','frequently','future','gather','general','government',
  'happen','important','include','increase','indicate','inform','involve','language',
  'listen','manage','mention','method','monitor','natural','notice','obtain','option',
  'organize','overcome','perform','position','prepare','present','prevent','process',
  'produce','project','provide','publish','purpose','quality','question','reason',
  'record','reduce','remember','remove','replace','require','research','respond',
  'result','return','reveal','review','search','section','select','solution','solve',
  'structure','success','suggest','support','surface','system','target','together',
  'understand','unique','usually','various','volume','welcome','whether','without',
  'absolute','abstract','accurate','adequate','adjacent','alternate','ambitious',
  'available','brilliant','capable','careful','certain','circular','classical',
  'conscious','consistent','constant','constructive','continuous','convenient',
  'creative','critical','crucial','cultural','deliberate','democratic','different',
  'diplomatic','direct','distinct','diverse','domestic','dominant','dynamic',
  'economic','effective','efficient','elaborate','elementary','emotional','empty',
  'equal','essential','evident','excellent','exclusive','executive','existing',
  'extensive','external','flexible','formal','fundamental','genuine','gradual',
  'grateful','horizontal','immediate','impractical','independent','indirect','initial',
  'intellectual','internal','limited','logical','meaningful','mental','moderate',
  'mutual','negative','neutral','obvious','official','original','passive','personal',
  'physical','positive','potential','primary','prior','private','productive','professional',
  'progressive','protective','public','rational','reasonable','relevant','reliable',
  'remarkable','responsible','scientific','secure','sensitive','separate','significant',
  'similar','simultaneous','single','special','specific','stable','standard','static',
  'substantial','technical','temporary','theoretical','traditional','ultimate','uniform',
  'universal','urgent','useful','valid','vertical','virtual','visible','voluntary',
  // ── Challenging Words ─────────────────────────────────────────────────────
  'abandonment','abbreviation','acceleration','accessibility','accountability',
  'acknowledgment','acquisition','administration','advertisement','affirmation',
  'approximately','architecture','arrangement','articulation','assassination',
  'authentication','authorization','autobiography','automatically','availability',
  'breakthrough','bureaucracy','calculation','catastrophe','celebration','certification',
  'characteristic','collaboration','commemoration','communication','compensation',
  'comprehension','concentration','confidential','congratulations','conservation',
  'consideration','constellation','contemporary','contribution','controversial',
  'conversation','coordination','corresponding','counterproductive','crystallization',
  'dedication','deliberation','demonstration','determination','differentiation',
  'disagreement','disappointment','disorganized','documentation','dramatization',
  'electromagnetic','embarrassment','encouragement','entertainment','entrepreneurial',
  'environmental','establishment','evaluation','examination','experimentation',
  'explanation','extraordinary','facilitation','flexibility','foundation','functionality',
  'generalization','geographical','globalization','hallucination','harmonization',
  'hypothetical','identification','illumination','imagination','implementation',
  'improvement','inconvenience','incorporation','individualization','infrastructure',
  'initialization','inspiration','integration','interpretation','investigation',
  'irresponsible','jurisdiction','justification','knowledgeable','liberalization',
  'manufacturing','maximization','memorization','misinterpretation','modernization',
  'multiplication','negotiation','nevertheless','normalization','notification',
  'objectification','optimization','organization','overwhelming','participation',
  'perseverance','personalization','philosophical','polarization','possibilities',
  'prioritization','productivity','pronunciation','psychological','qualification',
  'quantification','recommendation','reconciliation','reconsideration','redistribution',
  'reinforcement','relationship','representation','responsibility','restructuring',
  'satisfactorily','sophisticated','specification','standardization','straightforward',
  'subordination','subscription','substitution','superintendent','sustainability',
  'transformation','transportation','uncomfortable','understanding','unfortunately',
  'unification','universalization','unprecedented','unreliable','visualization',
  'vulnerability','workmanship','accomplishment','acknowledgement','administration',
  'advertisement','breakthrough','characteristic','collaboration','concentration',
  'consideration','constitutional','contradiction','controversial','correspondence',
  'demonstration','discrimination','disorganization','documentation','electromagnetic',
  'embarrassment','encouragement','establishment','experimentation','extraordinary',
  'generalization','globalization','harmonization','identification','implementation',
  'individualization','infrastructure','instantaneous','interpretation','investigation',
  'juxtaposition','knowledgeable','manufacturing','misinterpretation','modernization',
  'multiplication','nevertheless','normalization','objectification','overwhelming',
  'participation','perseverance','personalization','philosophical','possibilities',
  'prioritization','pronunciation','psychological','qualification','quantification',
  'recommendation','reconciliation','reinforcement','representation','responsibility',
  'restructuring','sophisticated','specification','standardization','subordination',
  'transformation','transportation','universalization','unprecedented','visualization',
  // ── Adjective-heavy words ────────────────────────────────────────────────
  'adventurous','affectionate','aggressive','alert','ambitious','amiable','ample',
  'animated','articulate','assertive','astute','attentive','authentic','balanced',
  'bold','boundless','bright','broad','buoyant','candid','capable','caring','cautious',
  'charismatic','cheerful','civic','clear','clever','coherent','colorful','committed',
  'compassionate','composed','confident','consistent','constructive','courageous',
  'courteous','creative','crisp','decisive','dedicated','dependable','deserving',
  'diligent','diplomatic','discerning','disciplined','eager','earnest','effective',
  'eloquent','empathetic','energetic','engaging','enthusiastic','ethical','exact',
  'exceptional','expressive','extraordinary','fair','faithful','fearless','flexible',
  'focused','forthright','friendly','fulfilling','generous','genuine','gifted',
  'graceful','grateful','grounded','hardworking','helpful','honest','hopeful','humble',
  'imaginative','impressive','independent','industrious','innovative','insightful',
  'inspiring','intelligent','intentional','intuitive','inventive','joyful','kind',
  'knowledgeable','lively','logical','loyal','mature','meticulous','mindful','motivated',
  'natural','noble','nurturing','objective','open','optimistic','organized','original',
  'passionate','patient','perceptive','persistent','playful','polished','positive',
  'practical','precise','proactive','productive','profound','progressive','punctual',
  'purposeful','quick','rational','receptive','reliable','resilient','resourceful',
  'respectful','responsible','thoughtful','trustworthy','understanding','versatile',
  // ── Abstract Concepts ────────────────────────────────────────────────────
  'truth','beauty','goodness','justice','liberty','equality','solidarity','fraternity',
  'peace','harmony','balance','order','chaos','complexity','simplicity','clarity',
  'meaning','purpose','value','worth','dignity','honor','virtue','morality','ethics',
  'knowledge','wisdom','understanding','insight','intuition','creativity','imagination',
  'reason','logic','argument','evidence','proof','certainty','doubt','belief','faith',
  'time','space','matter','energy','force','motion','change','continuity','causality',
  'existence','reality','possibility','necessity','contingency','identity','difference',
  'unity','multiplicity','whole','part','form','content','structure','process','system',
  'nature','culture','society','history','tradition','modernity','progress','regression',
  'power','authority','freedom','autonomy','dependence','cooperation','competition',
  'love','hate','fear','desire','hope','despair','joy','sorrow','anger','peace',
  'beauty','ugliness','good','evil','right','wrong','true','false','real','imaginary',
  // ── Common Verbs ─────────────────────────────────────────────────────────
  'accept','allow','appear','apply','approach','become','begin','belong','bring',
  'build','call','carry','choose','come','consider','continue','create','decide',
  'describe','develop','discuss','discover','draw','drive','enjoy','enter','expect',
  'explain','fall','feel','find','follow','forget','give','grow','happen','hear',
  'help','hold','imagine','include','indicate','involve','join','keep','know','learn',
  'leave','let','live','look','lose','love','make','mean','meet','move','need',
  'offer','open','pass','place','plan','play','point','provide','put','reach','read',
  'realize','receive','remain','remember','represent','return','seem','send','share',
  'show','sit','speak','spend','stand','stay','stop','suggest','support','take',
  'teach','think','turn','understand','use','wait','walk','want','watch','work','write',
  // ── Adverbs ──────────────────────────────────────────────────────────────
  'absolutely','actually','almost','already','also','always','anywhere','apparently',
  'approximately','automatically','carefully','certainly','clearly','completely',
  'constantly','correctly','currently','definitely','directly','easily','effectively',
  'especially','essentially','eventually','exactly','extremely','finally','frequently',
  'generally','gradually','highly','immediately','importantly','increasingly','indeed',
  'initially','instead','largely','likely','mainly','nearly','necessarily','never',
  'normally','obviously','often','only','originally','otherwise','particularly',
  'perfectly','personally','possibly','potentially','precisely','previously','probably',
  'properly','quickly','quietly','quite','rarely','really','recently','relatively',
  'roughly','seriously','significantly','simply','slowly','specifically','strongly',
  'suddenly','surely','technically','therefore','thoroughly','totally','typically',
  'ultimately','usually','very','virtually','usually','whether','widely','yet',
  // ── Prepositions & Conjunctions ──────────────────────────────────────────
  'about','above','across','after','against','along','among','around','because','before',
  'behind','below','beneath','beside','between','beyond','despite','during','except',
  'following','from','inside','instead','into','near','next','outside','over','past',
  'since','through','throughout','toward','under','until','upon','within','without',
  'although','and','because','before','but','either','however','if','neither','nor',
  'once','otherwise','since','so','than','then','though','unless','until','when',
  // ── Professions ──────────────────────────────────────────────────────────
  'accountant','actor','actress','administrator','advisor','agent','analyst','architect',
  'artist','astronaut','astronomer','athlete','author','baker','biologist','botanist',
  'builder','carpenter','chef','chemist','coach','consultant','curator','dancer',
  'dentist','designer','developer','director','doctor','economist','editor','educator',
  'electrician','engineer','entrepreneur','explorer','farmer','filmmaker','firefighter',
  'geographer','geologist','historian','illustrator','inventor','journalist','judge',
  'lawyer','librarian','linguist','manager','mathematician','mechanic','musician',
  'navigator','nurse','nutritionist','optician','painter','pharmacist','philosopher',
  'photographer','physicist','pilot','plumber','politician','professor','programmer',
  'psychologist','radiologist','researcher','scientist','sculptor','sociologist',
  'surgeon','surveyor','teacher','therapist','translator','veterinarian','writer',
  // ── Fun / Themed ─────────────────────────────────────────────────────────
  'cosmic','galactic','stellar','nebular','celestial','lunar','solar','orbital','astral',
  'ethereal','mystical','enchanted','legendary','mythical','immortal','divine',
  'radiant','luminous','brilliant','dazzling','glowing','sparkling','shimmering',
  'vibrant','vivid','colorful','magnificent','spectacular','breathtaking','incredible',
  'phenomenal','extraordinary','exceptional','remarkable','outstanding','impressive',
  'fantastic','wonderful','marvelous','gorgeous','splendid','majestic','glorious',
  'crystal','diamond','sapphire','emerald','ruby','amethyst','topaz','opal','pearl',
  'thunder','lightning','hurricane','tornado','tsunami','avalanche','earthquake','blizzard',
  'dragon','phoenix','unicorn','griffin','sphinx','leviathan','kraken','chimera',
  'adventure','quest','journey','expedition','exploration','discovery','treasure','legend',
  'galaxy','nebula','supernova','blackhole','asteroid','comet','satellite','exoplanet',
  'robot','android','cyborg','hologram','quantum','virtual','augmented','artificial',
  'wizard','sorcerer','enchantment','prophecy','constellation','labyrinth','dimension',
  'cascade','avalanche','momentum','velocity','trajectory','magnitude','resonance',
  'innovation','revolution','transformation','evolution','progression','emergence',
  'mystery','wonder','curiosity','fascination','amazement','astonishment','awe',
  'passion','dedication','perseverance','resilience','determination','ambition','drive',
  'harmony','symphony','melody','rhythm','cadence','flow','movement','dance','grace',
  'sunrise','sunset','moonrise','starlight','aurora','rainbow','prism','spectrum',
  'ocean','wave','tide','current','depth','surface','horizon','coastline','shoreline',
  // ── More Common Adjectives ────────────────────────────────────────────────
  'able','acceptable','actual','additional','afraid','aggregate','agreeable','alike',
  'alive','aloof','alternate','amazing','angry','anxious','apparent','applicable',
  'appropriate','apt','ardent','argent','arid','aromatic','artistic','asleep','average',
  'awesome','awkward','bad','bare','basic','beauteous','becoming','benign','best',
  'bitter','bland','blank','bleak','blind','blissful','bloodless','blunt','boisterous',
  'bold','bored','boring','boundless','breezy','broken','bubbly','burning','careful',
  'casual','central','cheap','cheerless','chilly','civic','classic','clean','clever',
  'clueless','coarse','colossal','common','compact','competent','concerned','confused',
  'cool','cordial','cozy','crispy','crowded','crucial','curious','cylindrical','decent',
  'delicate','dense','detailed','devout','dexterous','drab','dreary','dreamy','drowsy',
  'dull','earnest','easy','educated','elaborate','elegant','elite','enchanting','eternal',
  'exact','exciting','exotic','expert','extreme','faint','familiar','famous','fierce',
  'flat','foolish','forgiving','forward','fragile','frank','frantic','frugal','full',
  'gentle','gifted','grand','grassy','grim','grumpy','gusty','handsome','harsh','hasty',
  'hollow','hopeless','humble','icy','ideal','idle','ignorant','immense','important',
  'improper','inept','infinite','ingenious','innocent','insane','intact','intense',
  'joyous','juicy','keen','lame','lean','level','lively','low','lucky','magnificent',
  'mild','minimal','minor','misty','modest','moody','murky','naive','neat','nervous',
  'nimble','noble','noisy','normal','numb','obscure','odd','opaque','orderly','outgoing',
  'outstanding','petite','plain','pleasant','plentiful','polite','poor','powerful',
  'precious','profound','prominent','proper','pure','quaint','queasy','real','refined',
  'rigid','robust','roomy','rough','rugged','rustic','sacred','safe','sane','scenic',
  'shabby','shady','sharp','simple','sincere','skilled','slender','slight','slow',
  'sly','smart','solid','somber','sore','spare','sparse','spicy','steep','stiff',
  'strange','strict','stylish','suitable','sunny','super','sure','swift','tactful',
  'tense','tight','tired','tolerant','tough','tranquil','vast','verbose','vibrant',
  'vigilant','warm','weary','wild','wise','witty','worthy','zealous','zesty',
  // ── More Verbs ────────────────────────────────────────────────────────────
  'absorb','accelerate','access','accommodate','accumulate','achieve','acknowledge',
  'activate','adapt','administer','adopt','advocate','agree','allocate','alter','amend',
  'amplify','animate','anticipate','appreciate','assemble','assess','assign','assist',
  'associate','assume','assure','attach','attract','audit','authorize','automate',
  'balance','calculate','capture','categorize','certify','clarify','classify','collaborate',
  'communicate','compile','compress','configure','confirm','connect','consolidate',
  'construct','convert','cooperate','coordinate','correct','cultivate','customize',
  'delegate','detect','differentiate','distribute','document','duplicate','eliminate',
  'enable','establish','estimate','execute','filter','finalize','format','generate',
  'guide','handle','identify','illustrate','initiate','input','integrate','justify',
  'launch','link','maintain','manipulate','measure','minimize','moderate','navigate',
  'negotiate','observe','operate','outline','package','perform','plan','prioritize',
  'process','promote','protect','publish','qualify','quantify','register','regulate',
  'render','reset','resolve','restore','retrieve','save','schedule','secure','segment',
  'simplify','specify','store','submit','summarize','synchronize','test','track',
  'train','transfer','transform','translate','update','validate','verify','visualize',
  // ── Nouns – Office & Work ─────────────────────────────────────────────────
  'agenda','appointment','approval','archive','assessment','assignment','attendance',
  'audit','authorization','briefing','calendar','certificate','checklist','client',
  'colleague','conference','contract','cost','deadline','decision','delivery','department',
  'discussion','draft','duration','evaluation','feedback','filing','goal','guideline',
  'initiative','invoice','iteration','kickoff','launch','meeting','milestone','minutes',
  'objective','onboarding','overview','permission','phase','pipeline','policy','priority',
  'procedure','proposal','prototype','requirement','resource','revision','roadmap','role',
  'scope','session','specification','sprint','stakeholder','status','strategy','summary',
  'task','template','timeline','training','transition','update','user story','validation',
  // ── Nouns – Home & Daily Life ─────────────────────────────────────────────
  'alarm','bag','bin','blanket','box','breakfast','briefcase','brush','calendar','candle',
  'catalog','chair','closet','coffee','comb','container','cookbook','cupboard','curtain',
  'cushion','diary','dish','drawer','dust','envelope','exercise','folder','fridge','fruit',
  'furniture','gadget','gift','habit','hairbrush','hanger','jar','journal','kettle','key',
  'kitchen','lamp','laundry','list','magazine','mailbox','map','meal','memo','mirror',
  'notebook','organizer','outlet','oven','package','pen','pencil','photo','plan','planner',
  'plate','plug','pocket','pot','printer','rack','razor','remote','routine','ruler',
  'schedule','scissors','shelf','shower','soap','switch','tablet','telephone','toothbrush',
  'towel','tray','umbrella','utensil','wallet','wardrobe','watch','whiteboard','window',
  // ── Nouns – Outdoors & Nature ─────────────────────────────────────────────
  'acorn','algae','arable','arch','archipelago','bark','bay','bazaar','bed','bedrock',
  'bloom','blossom','boulder','bud','butte','canyon','clearing','cliff','copse','crag',
  'creek','crest','ditch','dune','dust','fauna','fern','field','flora','footpath',
  'frostbite','garden','glacier','glade','glen','gorge','grove','gulch','gust','habitat',
  'heath','hedge','hill','hollow','horizon','island','ivy','knoll','lagoon','landslide',
  'lava','ledge','lichen','limestone','marsh','mist','moss','mudflat','oasis','outcrop',
  'overhang','path','peat','pebble','peninsula','pine','plateau','pool','prairie','quarry',
  'ravine','reef','ridge','ripple','rock','root','sandbank','sandstone','scrub','sediment',
  'seep','shade','shoal','shrub','silhouette','slope','soil','spring','sprig','summit',
  'surf','terrain','thicket','trail','tributary','trunk','undergrowth','undergrowth',
  'updraft','valley','vine','waterfall','watershed','wetland','wilderness','windbreak',
  // ── Descriptive Phrases & Compound Words ─────────────────────────────────
  'airborne','airtight','all-around','backtrack','best-case','breakdown','breakthroughs',
  'buildup','bypass','catchphrase','crossroad','cutback','darkroom','daydream','deadline',
  'drawback','dropout','easygoing','fallback','feedback','flatmate','flyover','footstep',
  'framework','freelance','getaway','groundwork','halfway','hallmark','handshake',
  'headcount','headlight','highlight','homeward','inbox','inbound','insight','kickback',
  'landmark','layover','layout','leftover','lifestyle','linkage','lockdown','lookout',
  'mainstream','makeover','meltdown','mindset','network','newcomer','offset','onboard',
  'onset','outcome','outreach','overhaul','overlap','overload','overview','payoff',
  'phase-out','pipeline','playback','pushback','rollout','rundown','setback','shortcut',
  'shutdown','sidetrack','signup','slowdown','startup','stopover','streamline','takeaway',
  'takeoff','timeline','touchdown','turnover','underway','update','upgrade','upload',
  'upswing','uptake','upward','walkthrough','workaround','workflow','writeup',
  // ── Body Parts & Human Biology ────────────────────────────────────────────
  'ankle','arm','back','beard','bicep','blood','body','bone','brain','breath','calf',
  'cheek','chest','chin','collarbone','ear','elbow','eyelid','face','fat','finger',
  'fist','foot','forearm','forehead','gland','grip','hair','hand','head','heart',
  'heel','hip','jaw','joint','kidney','knee','knuckle','leg','lip','liver','lung',
  'muscle','nail','neck','nerve','nose','palm','pelvis','pulse','rib','shoulder',
  'skin','skull','sole','spine','stomach','tendon','thigh','throat','thumb','tissue',
  'toe','tongue','tooth','vein','waist','wrist',
  // ── Countries & Nationalities ─────────────────────────────────────────────
  'afghan','american','arabic','argentinian','australian','austrian','bangladeshi',
  'belgian','bolivian','brazilian','british','cambodian','canadian','chilean','chinese',
  'colombian','croatian','cuban','czech','danish','dutch','ecuadorian','egyptian',
  'ethiopian','finnish','french','german','ghanaian','greek','guatemalan','honduran',
  'hungarian','indian','indonesian','iranian','iraqi','irish','israeli','italian',
  'jamaican','japanese','jordanian','kazakh','kenyan','korean','laotian','latvian',
  'lebanese','libyan','lithuanian','mexican','mongolian','moroccan','myanmar','nepalese',
  'nigerian','norwegian','pakistani','peruvian','philippine','polish','portuguese',
  'romanian','russian','saudi','senegalese','serbian','singaporean','spanish','sudanese',
  'swedish','swiss','thai','tunisian','turkish','ukrainian','uruguayan','venezuelan',
  'vietnamese','zambian','zimbabwean',
  // ── More Abstract Nouns ───────────────────────────────────────────────────
  'abundance','achievement','admiration','adversity','ambiguity','ambition','ancestry',
  'appreciation','aspiration','authority','awareness','capability','certainty','challenge',
  'change','character','clarity','commitment','community','complexity','credibility',
  'criticism','curiosity','destiny','devotion','dignity','discipline','discovery',
  'diversity','durability','efficiency','empowerment','enthusiasm','equality','evolution',
  'excellence','experience','expertise','exploration','expression','failure','fairness',
  'flexibility','fortune','fulfillment','gratitude','guidance','humility','identity',
  'imagination','impact','importance','inclusion','influence','initiative','integrity',
  'intelligence','intuition','kindness','knowledge','leadership','legacy','loyalty',
  'meaning','mentality','mindfulness','motivation','nobility','obligation','opportunity',
  'optimism','organization','patience','perspective','possibility','potential','purpose',
  'quality','recognition','reflection','reliability','relevance','reputation','respect',
  'responsibility','satisfaction','self-awareness','sincerity','strength','success',
  'support','sustainability','sympathy','transparency','trustworthiness','uncertainty',
  'understanding','unity','urgency','validity','value','versatility','vision','vitality',
  // ── Action/State Adjectives ──────────────────────────────────────────────
  'abrupt','abstract','accessible','acclaimed','adaptive','affluent','agile','alert',
  'aligned','ambitious','analytical','appealing','assertive','attentive','balanced',
  'capable','caring','charismatic','civic','coherent','collaborative','compassionate',
  'competent','compelling','compliant','concise','confident','consistent','constructive',
  'controlled','courageous','courteous','credible','decisive','dedicated','deliberate',
  'dependable','devoted','diligent','discerning','disciplined','driven','dynamic','eager',
  'effective','efficient','eloquent','empathetic','energetic','engaging','enthusiastic',
  'ethical','exceptional','expressive','fair','faithful','fearless','flawless','focused',
  'forthright','friendly','fulfilling','genuine','gracious','grounded','hardworking',
  'helpful','honorable','humble','imaginative','impressive','insightful','inspiring',
  'intentional','intuitive','inventive','kind','logical','loyal','mature','meticulous',
  'mindful','motivated','natural','nurturing','objective','open-minded','optimistic',
  'organized','passionate','patient','perceptive','persistent','playful','positive',
  'practical','precise','proactive','productive','profound','progressive','punctual',
  'purposeful','rational','receptive','reliable','resilient','resourceful','responsive',
  'results-driven','self-aware','sincere','skillful','strategic','systematic','thoughtful',
  'trustworthy','versatile','visionary','willing','zealous',
  // ── Extra Common Words ────────────────────────────────────────────────────
  'across','against','agree','along','also','although','among','apart','around','away',
  'become','being','below','better','beyond','both','bring','built','carry','certain',
  'clear','close','comes','connect','cut','deal','did','does','down','each','early',
  'else','enough','even','ever','except','fall','feel','felt','few','fill','final',
  'find','five','following','four','full','gets','given','goes','going','gone',
  'great','grow','half','having','hold','home','hope','hot','idea','if','inside',
  'instead','itself','keep','kind','knew','lack','late','later','least','let',
  'likely','little','local','long','looking','lost','made','main','making','many',
  'matter','might','mind','missing','more','mostly','move','moving','much','nothing',
  'numbers','object','once','ones','others','outside','own','part','past','place',
  'plan','plus','point','possible','puts','quite','rather','really','rest','right',
  'same','sense','set','show','since','size','soon','sort','space','start','step',
  'still','such','sure','takes','ten','term','thing','think','those','thought',
  'three','through','told','toward','true','try','turn','twice','type','using',
  'view','want','ways','well','went','whatever','whole','wide','within','years',
];
