// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/keyboard-ui/Nebula.tsx": () => import("../components/mockups/keyboard-ui/Nebula.tsx"),
  "./components/mockups/keyboard-ui/Obsidian.tsx": () => import("../components/mockups/keyboard-ui/Obsidian.tsx"),
  "./components/mockups/keyboard-ui/Void.tsx": () => import("../components/mockups/keyboard-ui/Void.tsx")
};
