export type InstrumentClass =
  | 'piano' | 'guitar' | 'drums' | 'flute' | 'bass' | 'pad' | 'synth'
  | 'percussion' | 'violin' | 'trumpet' | 'organ' | 'saxophone' | 'harpsichord'
  | 'bass-ext' | 'accordion' | 'french-horn' | 'vocoder' | 'glockenspiel'
  | 'theremin' | 'acoustic-guitar' | 'vibraphone' | 'system';

export type KeyDef = {
  id: string;
  label: string;
  sub?: string;
  width?: number;
  instrumentClass?: InstrumentClass;
};

export const KEYBOARD_LAYOUT: KeyDef[][] = [
  // Row 0 - Function keys + system cluster
  [
    { id: 'Escape', label: 'Esc', width: 1, instrumentClass: 'system' },
    { id: 'F1', label: 'F1', instrumentClass: 'drums' },
    { id: 'F2', label: 'F2', instrumentClass: 'drums' },
    { id: 'F3', label: 'F3', instrumentClass: 'drums' },
    { id: 'F4', label: 'F4', instrumentClass: 'drums' },
    { id: 'F5', label: 'F5', instrumentClass: 'drums' },
    { id: 'F6', label: 'F6', instrumentClass: 'drums' },
    { id: 'F7', label: 'F7', instrumentClass: 'drums' },
    { id: 'F8', label: 'F8', instrumentClass: 'drums' },
    { id: 'F9', label: 'F9', instrumentClass: 'drums' },
    { id: 'F10', label: 'F10', instrumentClass: 'drums' },
    { id: 'F11', label: 'F11', instrumentClass: 'drums' },
    { id: 'F12', label: 'F12', instrumentClass: 'drums' },
    { id: 'PrintScreen', label: 'PrtSc', width: 1.2, instrumentClass: 'vocoder' },
    { id: 'ScrollLock', label: 'Scroll', width: 1.2, instrumentClass: 'glockenspiel' },
    { id: 'Pause', label: 'Pause', width: 1.2, instrumentClass: 'theremin' },
  ],
  // Row 1 - Numbers + nav cluster top + numpad top
  [
    { id: 'Backquote', label: '`', sub: '~', instrumentClass: 'flute' },
    { id: 'Digit1', label: '1', sub: '!', instrumentClass: 'guitar' },
    { id: 'Digit2', label: '2', sub: '@', instrumentClass: 'guitar' },
    { id: 'Digit3', label: '3', sub: '#', instrumentClass: 'guitar' },
    { id: 'Digit4', label: '4', sub: '$', instrumentClass: 'guitar' },
    { id: 'Digit5', label: '5', sub: '%', instrumentClass: 'guitar' },
    { id: 'Digit6', label: '6', sub: '^', instrumentClass: 'guitar' },
    { id: 'Digit7', label: '7', sub: '&', instrumentClass: 'guitar' },
    { id: 'Digit8', label: '8', sub: '*', instrumentClass: 'guitar' },
    { id: 'Digit9', label: '9', sub: '(', instrumentClass: 'guitar' },
    { id: 'Digit0', label: '0', sub: ')', instrumentClass: 'guitar' },
    { id: 'Minus', label: '-', sub: '_', instrumentClass: 'flute' },
    { id: 'Equal', label: '=', sub: '+', instrumentClass: 'flute' },
    { id: 'Backspace', label: '⌫', width: 2.1, instrumentClass: 'system' },
    { id: 'Insert', label: 'Ins', instrumentClass: 'saxophone' },
    { id: 'Home', label: 'Home', instrumentClass: 'harpsichord' },
    { id: 'PageUp', label: 'PgUp', instrumentClass: 'accordion' },
    { id: 'NumLock', label: 'Num', instrumentClass: 'acoustic-guitar' },
    { id: 'NumpadDivide', label: '/', instrumentClass: 'percussion' },
    { id: 'NumpadMultiply', label: '*', instrumentClass: 'percussion' },
    { id: 'NumpadSubtract', label: '-', instrumentClass: 'percussion' },
  ],
  // Row 2 - QWERTY
  [
    { id: 'Tab', label: 'Tab', width: 1.6, instrumentClass: 'trumpet' },
    { id: 'KeyQ', label: 'Q', instrumentClass: 'piano' },
    { id: 'KeyW', label: 'W', instrumentClass: 'piano' },
    { id: 'KeyE', label: 'E', instrumentClass: 'piano' },
    { id: 'KeyR', label: 'R', instrumentClass: 'piano' },
    { id: 'KeyT', label: 'T', instrumentClass: 'piano' },
    { id: 'KeyY', label: 'Y', instrumentClass: 'piano' },
    { id: 'KeyU', label: 'U', instrumentClass: 'piano' },
    { id: 'KeyI', label: 'I', instrumentClass: 'piano' },
    { id: 'KeyO', label: 'O', instrumentClass: 'piano' },
    { id: 'KeyP', label: 'P', instrumentClass: 'piano' },
    { id: 'BracketLeft', label: '[', sub: '{', instrumentClass: 'flute' },
    { id: 'BracketRight', label: ']', sub: '}', instrumentClass: 'flute' },
    { id: 'Backslash', label: '\\', sub: '|', width: 1.5, instrumentClass: 'flute' },
    { id: 'Delete', label: 'Del', instrumentClass: 'organ' },
    { id: 'End', label: 'End', instrumentClass: 'bass-ext' },
    { id: 'PageDown', label: 'PgDn', instrumentClass: 'french-horn' },
    { id: 'Numpad7', label: '7', sub: 'Home', instrumentClass: 'percussion' },
    { id: 'Numpad8', label: '8', sub: '↑', instrumentClass: 'percussion' },
    { id: 'Numpad9', label: '9', sub: 'PgUp', instrumentClass: 'percussion' },
    { id: 'NumpadAdd', label: '+', width: 1, instrumentClass: 'percussion' },
  ],
  // Row 3 - ASDF
  [
    { id: 'CapsLock', label: 'Caps', width: 1.8, instrumentClass: 'violin' },
    { id: 'KeyA', label: 'A', instrumentClass: 'piano' },
    { id: 'KeyS', label: 'S', instrumentClass: 'piano' },
    { id: 'KeyD', label: 'D', instrumentClass: 'piano' },
    { id: 'KeyF', label: 'F', instrumentClass: 'piano' },
    { id: 'KeyG', label: 'G', instrumentClass: 'piano' },
    { id: 'KeyH', label: 'H', instrumentClass: 'piano' },
    { id: 'KeyJ', label: 'J', instrumentClass: 'piano' },
    { id: 'KeyK', label: 'K', instrumentClass: 'piano' },
    { id: 'KeyL', label: 'L', instrumentClass: 'piano' },
    { id: 'Semicolon', label: ';', sub: ':', instrumentClass: 'flute' },
    { id: 'Quote', label: "'", sub: '"', instrumentClass: 'flute' },
    { id: 'Enter', label: '↵ Enter', width: 2.3, instrumentClass: 'piano' },
    { id: 'Numpad4', label: '4', sub: '←', instrumentClass: 'percussion' },
    { id: 'Numpad5', label: '5', instrumentClass: 'percussion' },
    { id: 'Numpad6', label: '6', sub: '→', instrumentClass: 'percussion' },
  ],
  // Row 4 - ZXCV
  [
    { id: 'ShiftLeft', label: '⇧ Shift', width: 2.4, instrumentClass: 'system' },
    { id: 'KeyZ', label: 'Z', instrumentClass: 'piano' },
    { id: 'KeyX', label: 'X', instrumentClass: 'piano' },
    { id: 'KeyC', label: 'C', instrumentClass: 'piano' },
    { id: 'KeyV', label: 'V', instrumentClass: 'piano' },
    { id: 'KeyB', label: 'B', instrumentClass: 'piano' },
    { id: 'KeyN', label: 'N', instrumentClass: 'piano' },
    { id: 'KeyM', label: 'M', instrumentClass: 'piano' },
    { id: 'Comma', label: ',', sub: '<', instrumentClass: 'flute' },
    { id: 'Period', label: '.', sub: '>', instrumentClass: 'flute' },
    { id: 'Slash', label: '/', sub: '?', instrumentClass: 'flute' },
    { id: 'ShiftRight', label: '⇧ Shift', width: 2.8, instrumentClass: 'system' },
    { id: 'ArrowUp', label: '↑', instrumentClass: 'synth' },
    { id: 'Numpad1', label: '1', sub: 'End', instrumentClass: 'percussion' },
    { id: 'Numpad2', label: '2', sub: '↓', instrumentClass: 'percussion' },
    { id: 'Numpad3', label: '3', sub: 'PgDn', instrumentClass: 'percussion' },
    { id: 'NumpadEnter', label: 'Ent', width: 1, instrumentClass: 'piano' },
  ],
  // Row 5 - Modifiers + Space + Arrows
  [
    { id: 'ControlLeft', label: 'Ctrl', width: 1.5, instrumentClass: 'pad' },
    { id: 'MetaLeft', label: '⊞', width: 1.3, instrumentClass: 'vibraphone' },
    { id: 'AltLeft', label: 'Alt', width: 1.3, instrumentClass: 'pad' },
    { id: 'Space', label: '♪ Space', width: 7, instrumentClass: 'bass' },
    { id: 'AltRight', label: 'Alt', width: 1.3, instrumentClass: 'pad' },
    { id: 'MetaRight', label: '⊞', width: 1.3, instrumentClass: 'vibraphone' },
    { id: 'ContextMenu', label: '☰', width: 1.3, instrumentClass: 'system' },
    { id: 'ControlRight', label: 'Ctrl', width: 1.5, instrumentClass: 'pad' },
    { id: 'ArrowLeft', label: '←', instrumentClass: 'synth' },
    { id: 'ArrowDown', label: '↓', instrumentClass: 'synth' },
    { id: 'ArrowRight', label: '→', instrumentClass: 'synth' },
    { id: 'Numpad0', label: '0', sub: 'Ins', width: 2, instrumentClass: 'percussion' },
    { id: 'NumpadDecimal', label: '.', sub: 'Del', instrumentClass: 'percussion' },
  ],
];

// ── Mobile landscape layout (5 rows, no numpad / nav cluster) ──────────────
// Designed for phones in landscape: ~14–15 flex-units per row so every key
// is at least 44 px wide on a 375 px-wide device.
export const MOBILE_LANDSCAPE_LAYOUT: KeyDef[][] = [
  // Row 0 — numbers
  [
    { id: 'Backquote', label: '`',  sub: '~',  instrumentClass: 'flute'  },
    { id: 'Digit1',    label: '1',  sub: '!',  instrumentClass: 'guitar' },
    { id: 'Digit2',    label: '2',  sub: '@',  instrumentClass: 'guitar' },
    { id: 'Digit3',    label: '3',  sub: '#',  instrumentClass: 'guitar' },
    { id: 'Digit4',    label: '4',  sub: '$',  instrumentClass: 'guitar' },
    { id: 'Digit5',    label: '5',  sub: '%',  instrumentClass: 'guitar' },
    { id: 'Digit6',    label: '6',  sub: '^',  instrumentClass: 'guitar' },
    { id: 'Digit7',    label: '7',  sub: '&',  instrumentClass: 'guitar' },
    { id: 'Digit8',    label: '8',  sub: '*',  instrumentClass: 'guitar' },
    { id: 'Digit9',    label: '9',  sub: '(',  instrumentClass: 'guitar' },
    { id: 'Digit0',    label: '0',  sub: ')',  instrumentClass: 'guitar' },
    { id: 'Minus',     label: '-',  sub: '_',  instrumentClass: 'flute'  },
    { id: 'Equal',     label: '=',  sub: '+',  instrumentClass: 'flute'  },
    { id: 'Backspace', label: '⌫',  width: 2,  instrumentClass: 'system' },
  ],
  // Row 1 — QWERTY
  [
    { id: 'Tab',          label: 'Tab', width: 1.4, instrumentClass: 'trumpet' },
    { id: 'KeyQ',         label: 'Q',               instrumentClass: 'piano'   },
    { id: 'KeyW',         label: 'W',               instrumentClass: 'piano'   },
    { id: 'KeyE',         label: 'E',               instrumentClass: 'piano'   },
    { id: 'KeyR',         label: 'R',               instrumentClass: 'piano'   },
    { id: 'KeyT',         label: 'T',               instrumentClass: 'piano'   },
    { id: 'KeyY',         label: 'Y',               instrumentClass: 'piano'   },
    { id: 'KeyU',         label: 'U',               instrumentClass: 'piano'   },
    { id: 'KeyI',         label: 'I',               instrumentClass: 'piano'   },
    { id: 'KeyO',         label: 'O',               instrumentClass: 'piano'   },
    { id: 'KeyP',         label: 'P',               instrumentClass: 'piano'   },
    { id: 'BracketLeft',  label: '[', sub: '{',      instrumentClass: 'flute'   },
    { id: 'BracketRight', label: ']', sub: '}',      instrumentClass: 'flute'   },
    { id: 'Backslash',    label: '\\', sub: '|', width: 1.4, instrumentClass: 'flute' },
  ],
  // Row 2 — ASDF
  [
    { id: 'CapsLock', label: 'Caps',    width: 1.7, instrumentClass: 'violin' },
    { id: 'KeyA',     label: 'A',                   instrumentClass: 'piano'  },
    { id: 'KeyS',     label: 'S',                   instrumentClass: 'piano'  },
    { id: 'KeyD',     label: 'D',                   instrumentClass: 'piano'  },
    { id: 'KeyF',     label: 'F',                   instrumentClass: 'piano'  },
    { id: 'KeyG',     label: 'G',                   instrumentClass: 'piano'  },
    { id: 'KeyH',     label: 'H',                   instrumentClass: 'piano'  },
    { id: 'KeyJ',     label: 'J',                   instrumentClass: 'piano'  },
    { id: 'KeyK',     label: 'K',                   instrumentClass: 'piano'  },
    { id: 'KeyL',     label: 'L',                   instrumentClass: 'piano'  },
    { id: 'Semicolon',label: ';',  sub: ':',         instrumentClass: 'flute'  },
    { id: 'Quote',    label: "'",  sub: '"',         instrumentClass: 'flute'  },
    { id: 'Enter',    label: '↵',  width: 2.1,       instrumentClass: 'piano'  },
  ],
  // Row 3 — ZXCV
  [
    { id: 'ShiftLeft',  label: '⇧', width: 2.2, instrumentClass: 'system' },
    { id: 'KeyZ',       label: 'Z',              instrumentClass: 'piano'  },
    { id: 'KeyX',       label: 'X',              instrumentClass: 'piano'  },
    { id: 'KeyC',       label: 'C',              instrumentClass: 'piano'  },
    { id: 'KeyV',       label: 'V',              instrumentClass: 'piano'  },
    { id: 'KeyB',       label: 'B',              instrumentClass: 'piano'  },
    { id: 'KeyN',       label: 'N',              instrumentClass: 'piano'  },
    { id: 'KeyM',       label: 'M',              instrumentClass: 'piano'  },
    { id: 'Comma',      label: ',', sub: '<',    instrumentClass: 'flute'  },
    { id: 'Period',     label: '.', sub: '>',    instrumentClass: 'flute'  },
    { id: 'Slash',      label: '/', sub: '?',    instrumentClass: 'flute'  },
    { id: 'ShiftRight', label: '⇧', width: 2.6, instrumentClass: 'system' },
  ],
  // Row 4 — modifiers + space + arrows
  [
    { id: 'ControlLeft', label: 'Ctrl', width: 1.4, instrumentClass: 'pad'       },
    { id: 'AltLeft',     label: 'Alt',  width: 1.2, instrumentClass: 'pad'       },
    { id: 'Space',       label: '♪',    width: 7,   instrumentClass: 'bass'      },
    { id: 'AltRight',    label: 'Alt',  width: 1.2, instrumentClass: 'pad'       },
    { id: 'ArrowLeft',   label: '←',               instrumentClass: 'synth'     },
    { id: 'ArrowDown',   label: '↓',               instrumentClass: 'synth'     },
    { id: 'ArrowUp',     label: '↑',               instrumentClass: 'synth'     },
    { id: 'ArrowRight',  label: '→',               instrumentClass: 'synth'     },
  ],
];

export const INSTRUMENT_COLORS: Record<string, string> = {
  piano:           '#33a1ff',
  guitar:          '#ff9f1c',
  drums:           '#ff5b55',
  flute:           '#38e29d',
  bass:            '#b45cff',
  pad:             '#5f6bff',
  synth:           '#ffd447',
  percussion:      '#ff7eb3',
  violin:          '#e05cff',
  trumpet:         '#ffdc00',
  organ:           '#ff6f3c',
  saxophone:       '#00cfff',
  harpsichord:     '#c8ff80',
  'bass-ext':      '#7040ff',
  accordion:       '#ff9060',
  'french-horn':   '#80dfb0',
  vocoder:         '#ff80d0',
  glockenspiel:    '#e0ffff',
  theremin:        '#c0f0ff',
  'acoustic-guitar': '#d4a96a',
  vibraphone:      '#fffb80',
  system:          'rgba(255,255,255,0.3)',
};

export const INSTRUMENT_NAMES: Record<string, string> = {
  piano:           '🎹 Piano',
  guitar:          '🎸 Electric Guitar',
  drums:           '🥁 Drums',
  flute:           '🪈 Flute',
  bass:            '🎸 Bass',
  pad:             '🌊 Ambient Pads',
  synth:           '🎛 Synth',
  percussion:      '🪘 Percussion',
  violin:          '🎻 Violin',
  trumpet:         '🎺 Trumpet',
  organ:           '🎼 Organ',
  saxophone:       '🎷 Saxophone',
  harpsichord:     '🎹 Harpsichord',
  'bass-ext':      '🎸 Electric Bass',
  accordion:       '🪗 Accordion',
  'french-horn':   '🎺 French Horn',
  vocoder:         '🎙 Vocoder',
  glockenspiel:    '🔔 Glockenspiel',
  theremin:        '🌊 Theremin',
  'acoustic-guitar': '🎸 Acoustic Guitar',
  vibraphone:      '🎵 Vibraphone',
};
